on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build_skeletyl:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    name: Build Skeletyl
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache west modules
        uses: actions/cache@v3
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build (Skeletyl Left)
        run: west build -s zmk/app -b seeeduino_xiao_ble -- -DSHIELD=tbkmini_left -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Skeletyl Left Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 skeletyl_left_xiao.uf2
      - name: Archive (Skeletyl Left)
        uses: actions/upload-artifact@v3
        with:
          name: skeletyl_firmware
          path: skeletyl_left_xiao.uf2
      - name: West Build (Skeletyl Right)
        run: west build --pristine -s zmk/app -b seeeduino_xiao_ble -- -DSHIELD=tbkmini_right -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Skeletyl Right Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 skeletyl_right_xiao.uf2
      - name: Archive (Skeletyl Right)
        uses: actions/upload-artifact@v3
        with:
          name: skeletyl_firmware
          path: skeletyl_right_xiao.uf2


